### ISSUE TITLE
Implicit LIMIT of 10000 on queries with no LIMIT clause

### ISSUE THREAD

**Issue by reversefold** [crate/crate-python#139]
I ran a query with no LIMIT clause which should have returned nearly 60000 records but got only 10000 returned. Adding LIMIT 60000 returned all of the records. There should be no implicit LIMIT when no LIMIT was requested.

**Comment by chaudum** [comment]
Crate has a hard coded [internal select limit of 10000](https://github.com/crate/crate/blob/master/core/src/main/java/io/crate/Constants.java#L40) because of two reasons:
* prevent performance issues, e.g. when unintendedly fetching without LIMIT
* Crate does not support paging to the clients yet, which could lead to out of memory exceptions when selecting a large amount of data.

The latter is the more important reason.

**Comment by mfussenegger** [comment]
Closing this here since the implicit limit isn't something that crate-python adds but is a server side thing.
There is also an issue in the crate repo about streaming data: https://github.com/crate/crate/issues/1226
